language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dockerbwong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockerbwong/react-test npm test

after_success:
  - docker build -t dockerbwong/multi-client ./client
  - docker build -t dockerbwong/multi-nginx ./nginx
  - docker build -t dockerbwong/multi-server ./server
  - docker build -t dockerbwong/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dockerbwong/multi-client
  - docker push dockerbwong/multi-nginx
  - docker push dockerbwong/multi-server
  - docker push dockerbwong/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-2
  bucket_name: elasticbeanstalk-us-east-2-877943543164
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
